---

- name: mongo data directory
  file: name={{mongo.data_dir}} state=directory

- name: create docker-compose/db directory
  file: name="{{base}}/docker-compose/db" state=directory

- name: create db haproxy configuration path
  file: name="{{base}}/etc/haproxy/db" state=directory

- name: generate db haproxy configuration file
  template: src="etc/haproxy/db/haproxy.cfg.j2" dest="{{base}}/etc/haproxy/db/haproxy.cfg"


- name: generate docker-compose file
  template: src="docker-compose/db/up.yml.j2" dest="{{base}}/docker-compose/db/up.yml"

- name: db docker-compose up
  command: "docker-compose --project-name db up -d --force-recreate"
  environment:
    COMPOSE_FILE: "{{base}}/docker-compose/db/up.yml"
