---

ansible_user: root

# xenial doesn't come with python2 https://groups.google.com/forum/#!topic/Ansible-project/DUKzTho3OCI
ansible_python_interpreter: /usr/bin/python2.7

env: unknown
org: "cairo"
base: "/{{org}}"
git_base: "{{base}}/git"
locale: "en_US.UTF-8"
network: "{{org}}"
network_device: "eth1"
network_interface: "ansible_{{network_device}}"

version:
  docker_engine: "1.12.1"
  docker_compose: "1.8.1"
  mongo: "mongo:latest"
  redis: "redis:latest"
  node: "node:latest"
  haproxy: "haproxy:latest"
  nginx: "nginx:latest"
  consul: "consul:latest"

conf:
  # docker
  docker_apt_keyserver: "hkp://p80.pool.sks-keyservers.net:80"
  docker_apt_keyid: "58118E89F3A912897C070ADBF76221572C52609D"
  docker_apt_repository: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
  docker_apt_prerequisites:
    - apt-transport-https
    - ca-certificates
  docker_systemd_dir: "/etc/systemd/system/docker.service.d"

mongo:
  data_dir: /var/mongo/data/db
  port: 27017
  db: chat
  user: admin
  password: admin

redis:
  port: 6379

consul:
  data_dir: /var/consul/data


default_service_run_mode: "production"
default_service_branch: "HEAD"
default_service_main_script: "server.js"

services:
  -
    name: "chat.io"
    repo: "https://github.com/hkarim/chat.io"
    container_name: "chatio"
    branch: "{{default_service_branch}}"
    work_dir: "."
    mode: "{{default_service_run_mode}}"
    main_script: "{{default_service_main_script}}"
    proxy: True
    bind_port: 3000
    protocol: http
    prefixes: ["/"]
