---

# install python 2, xenial doesn't come with python2
- name: apt-get update
  raw: sudo apt-get update -qq
- name: install python 2.7
  raw: sudo apt-get install -qq python2.7

- name: set machine locale
  lineinfile: dest=/etc/environment line="LC_ALL=\"{{locale}}\"" state=present

#- name: machine kernel options
#  lineinfile: dest=/etc/default/grub line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"' state=present
#

- name: install curl
  apt: name=curl state=present

- name: install git
  apt: name=git state=present

- name: install python pip
  apt: name=python-pip state=present

- name: git base dir
  file: name="{{git_base}}" state=directory

- name: project base dir
  file: name="{{base}}" state=directory
