---

- name: create service docker-compose path
  file: name="{{base}}/docker-compose/service" state=directory

- name: generate service docker compose file
  template: src="docker-compose/service/up.yml.j2" dest="{{base}}/docker-compose/service/up.yml"

- name: service docker-compose up
  command: "docker-compose --project-name {{inventory_hostname}} up -d --build --force-recreate"
  environment:
    COMPOSE_FILE: "{{base}}/docker-compose/service/up.yml"

- name: service docker-compose scale
  command: "docker-compose --project-name {{inventory_hostname}} scale {{item.key}}={{item.value}}"
  environment:
    COMPOSE_FILE: "{{base}}/docker-compose/service/up.yml"
  with_dict: "{{scale[inventory_hostname]}}"
