---

- name: stop overlay networked containers
  command: "docker stop {{item}}"
  ignore_errors: True
  with_items: '{{stop_containers}}'

- name: remove overlay networked containers
  command: "docker rm {{item}}"
  ignore_errors: True
  with_items: '{{rm_containers}}'

- name: remove stale network entries
  command: "docker network disconnect -f {{network}} {{item}}"
  ignore_errors: True
  with_items: '{{rm_containers}}'

- name: drop overlay networks
  command: "docker network rm {{item}}"
  ignore_errors: True
  with_items: '{{rm_networks}}'
